---
- name: Upgrade Pre-Check Playbook for Cisco IOS and IOS-XE Devices
  hosts: all
  gather_facts: no
  vars:
    ansible_command_timeout: 10800
    scp_server: "{{ scp_server }}"
    scp_username: "{{ scp_username }}"
    scp_password: "{{ scp_password }}"
    new_ios_version: "{{ new_ios_version }}"
    new_ios_image: "{{ new_image_name }}"
    new_image_md5: "{{ new_image_md5 }}"

  tasks:
    - name: Get all elements hardware device
      cisco.ios.ios_facts:
        gather_subset: hardware
      register: pre_upgrade_facts

    - name: Display pre-upgrade facts
      debug:
        var: pre_upgrade_facts

    - name: Check current IOS version
      ansible.builtin.set_fact:    
        current_ios_version: "{{ pre_upgrade_facts.ansible_facts.ansible_net_version }}"

    - name: Display current IOS version
      debug:
        msg: 
          - "Current IOS Version: {{ current_ios_version }}"
          - "New IOS Version: {{ new_ios_version }}"

    - name: Stop Playbook if current version is same as new version
      ansible.builtin.fail:
        msg: "Current IOS version {{ current_ios_version }} is the same as the new version {{ new_ios_version }}. Upgrade not required."
      when: current_ios_version == new_ios_version

    - name: Check available memory
      ansible.builtin.set_fact:
        avl_mem: "{{ pre_upgrade_facts['ansible_facts']['ansible_net_filesystems_info']['bootflash:']['spacefree_kb'] }}"

    - name: Display available memory
      debug:
        msg: "Available memory: {{ (avl_mem | int / 1024 / 1024) | round(2) }} GB"

    - name: Stop playbook if memory is insufficient for new image
      block:
        - ansible.builtin.fail:
            msg: "Insufficient memory: Available memory is {{ avl_mem }} KB, which is less than required for new image."
          when: avl_mem | int < 2000000  # Assuming 2GB is required for the new image
      rescue:
        - name: Display insufficient memory warning
          debug:
            msg: "Warning: Available memory is less than required for the new image. Please free up space and try again."

    - name: Get IP Routing Table Summary
      cisco.ios.ios_command:
        commands: "show ip route summary"
      register: pre_route_raw

    - name: Display IP Routing Table Summary
      debug:
        var: pre_route_raw.stdout_lines

    - name: Extract Total Routes (Networks + Subnets)
      ansible.builtin.set_fact:
        pre_total_networks: "{{ (pre_route_raw.stdout[0] | regex_search('Total.*') | split)[1] }}"
        pre_total_subnets: "{{ (pre_route_raw.stdout[0] | regex_search('Total.*') | split)[2] }}"

    - name: Display Total Networks and Subnets
      debug:
        msg:
          - "Total Networks: {{ pre_total_networks }}"
          - "Total Subnets: {{ pre_total_subnets }}"

    - name: Save stats to worflow
      ansible.builtin.set_stats:
        data:
          snapshot_networks: "{{ pre_total_networks }}"
          snapshot_subnets: "{{ pre_total_subnets }}"
        per_host: yes


    - name: Check current register status
      cisco.ios.ios_command:
        commands:
          - show version | include Configuration register
      register: reg_status

    - name: Display current register status
      debug:
        msg: "Current Configuration Register: {{ reg_status.stdout[0].split()[-1] }}"

    - name: Set fact for current register
      ansible.builtin.set_fact:
        current_register: "{{ reg_status.stdout[0].split()[-1] }}"

    - name: Change to boot from flash if register is not 0x2102
      cisco.ios.ios_config:
        lines:
          - config-register 0x2102
      when: current_register != '0x2102'

    - name: Check if new IOS image already exists on device
      cisco.ios.ios_command:
        commands:
          - "show flash: | include {{ new_ios_image }}"
      register: image_check
      failed_when: false

    - name: Handle IOS image copy and verification
      block:
        - name: Copy new IOS image to device using SCP
          cisco.ios.ios_command:
            commands:
              - command: 'copy scp://{{ scp_username }}:{{ scp_password }}@{{ scp_server }}/{{ new_ios_image }} flash:/{{ new_ios_image }}'
                prompt: 'Destination filename \[{{ new_ios_image }}\]?'
                answer: '{{ new_ios_image }}'
          register: image_copy_result
          ignore_errors: yes

        - name: Display image copy success message
          debug:
            msg: "Image copy successful: {{ image_copy_result }}"
          ignore_errors: yes

        - name: Reset connection to remove buffered output
          ansible.builtin.meta: reset_connection

        - name: Check if image copy was successful
          cisco.ios.ios_command:
            commands:
              - "show flash: | include {{ new_ios_image }}"
          register: post_copy_check
          ignore_errors: yes
        
        - name: Diplay post copy check result
          debug:
            var: post_copy_check

      when: image_check.stdout[0] == ""

    - name: Display message if image already exists
      debug:
        msg: "The new IOS image {{ new_ios_image }} already exists on the device. Skipping copy step."
      when: image_check.stdout[0] != ""
    
    - name: Verify MD5 checksum of the new IOS image
      cisco.ios.ios_command:
        commands:
          - "verify /md5 flash:/{{ new_ios_image }} {{ new_image_md5 }}"
      register: md5_result

    - name: Display MD5 verification result
      debug:
        var: md5_result

    - name: Fetch MD5_result
      ansible.builtin.set_fact:
        caculated_md5_hash: "{{ md5_result.stdout[0] | regex_findall('.*\\s(\\S+)') }}"

    - name: Display calculated MD5 hash
      debug:
        msg: "Calculated MD5 Hash: {{ caculated_md5_hash[1] }}"

    - name: Compare MD5 checksum
      ansible.builtin.assert:
        that:
          - "{{ caculated_md5_hash[1] == new_image_md5 }}"
        fail_msg: "MD5 checksum verification failed. The image may be corrupted."
        success_msg: "MD5 checksum verification successful. The image is valid."
    
