---
- name: Upgrade Pre-Check Playbook for Cisco IOS and IOS-XE Devices
  hosts: all
  gather_facts: no
  vars:
    ansible_command_timeout: 1800
    scp_server: "{{ scp_server }}"
    scp_username: "{{ scp_username }}"
    scp_password: "{{ scp_password }}"
    new_ios_version: "{{ new_ios_version }}"
    new_ios_image: "{{ new_image_name }}"
    new_image_md5: "{{ new_image_md5 }}"

  tasks:
    - name: Get all elements hardware device
      cisco.ios.ios_facts:
        gather_subset: hardware
      register: pre_upgrade_facts

    - name: Display pre-upgrade facts
      debug:
        var: pre_upgrade_facts

    - name: Check current IOS version
      ansible.builtin.set_fact:    
        current_ios_version: "{{ pre_upgrade_facts.ansible_facts.ansible_net_version }}"

    - name: Display current IOS version
      debug:
        msg: 
          - "Current IOS Version: {{ current_ios_version }}"
          - "New IOS Version: {{ new_ios_version }}"

    - name: Stop Playbook if current version is same as new version
      ansible.builtin.fail:
        msg: "Current IOS version {{ current_ios_version }} is the same as the new version {{ new_ios_version }}. Upgrade not required."
      when: current_ios_version == new_ios_version


    - name: Check available flash memory
      cisco.ios.ios_facts:
        gather_subset: storage
      register: storage_facts

    - name: Display storage facts
      debug:
        var: storage_facts
