---
- name: Upgrade Pre-Check Playbook for Cisco IOS and IOS-XE Devices
  hosts: all
  gather_facts: no
  vars:
    ansible_command_timeout: 1800
    scp_server: "{{ scp_server }}"
    scp_username: "{{ scp_username }}"
    scp_password: "{{ scp_password }}"
    new_ios_version: "{{ new_ios_version }}"
    new_ios_image: "{{ new_image_name }}"
    new_image_md5: "{{ new_image_md5 }}"
    
  tasks:
    - name: Backup configuration before upgrade
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          dir_path: "{{ playbook_dir }}"
          filename: "backup_{{ inventory_hostname }}_config_{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}.cfg"
      register: backup_result

    - name: Display backup result
      debug:
        var: backup_result['backup_path']
    
    - name: use scp to transfer backup to scp server
      ansible.builtin.command:
        cmd: sshpass -p '{{ scp_password }}' scp -o StrictHostKeyChecking=no {{ backup_result['backup_path'] }} {{ scp_username }}@{{ scp_server }}:backups/
      delegate_to: localhost
      no_log: true
