---
- name: Upgrade Bundle Mode IOS Device
  hosts: all
  gather_facts: yes
  vars:
    ansible_command_timeout: 30
    scp_server: "{{ scp_server }}"
    scp_username: "{{ scp_username }}"
    scp_password: "{{ scp_password }}"
    new_ios_version: "{{ new_ios_version }}"
    new_ios_image: "{{ new_image_name }}"
    new_image_md5: "{{ new_image_md5 }}"
    
  tasks:
    - name: Collect facts to get system information
      ansible.builtin.setup:
        filter:
          - ansible_date_time

    - name: Display collected facts
      debug:
        var: ansible_date_time

    - name: Backup configuration before upgrade
      cisco.ios.ios_command:
        commands: 
          - command: copy running-config startup-config
            prompt: 'Destination filename \[startup-config\]?'
            answer: "\n"

    - name: Send configuration backup to SCP server
      cisco.ios.ios_command:
        commands:
          - command: "copy startup-config scp://{{ scp_username }}:{{ scp_password }}@{{ scp_server }}/backups/{{ inventory_hostname }}_config_{{ ansible_date_time.iso8601 | replace(':', '-') }}.cfg\r\r\r"
            prompt: 
              - 'Address or name of remote host .*'
              - 'Destination username .*'
              - 'Destination filename .*'
            answer: 
              - "\r"
      register: scp_backup_result

    - name: Display SCP backup result
      debug:
        var: scp_backup_result

    - name: Check backup success
      ansible.builtin.assert:
        that:
          - "'bytes copied' in  scp_backup_result.stdout[0] "
        fail_msg: "Configuration backup failed. Aborting upgrade process."
        success_msg: "Configuration backup successful."

    - name: Set boot system - bundle mode
      cisco.ios.ios_config:
        lines:
          - "no boot system"
          - "boot system flash:{{ new_ios_image }}"
        save_when: modified

    - name: Show boot current setup
      cisco.ios.ios_command:
        commands:
          - show boot
      register: boot_config_result

    - name: Reloading the device to apply new boot system
      cisco.ios.ios_command:
        commands:
          - command: 'reload'
            prompt: 'confirm'
            answer: 'y'

    - name: Wait for 10 minutes and retry connection
      ansible.builtin.wait_for_connection:
        delay: 600
        timeout: 1800
        sleep: 60

    - name: Get all elements hardware device
      cisco.ios.ios_facts:
        gather_subset: hardware
      register: pre_upgrade_facts

    - name: Check new IOS version
      ansible.builtin.set_fact:    
        ios_version: "{{ pre_upgrade_facts.ansible_facts.ansible_net_version }}"

    - name: Display new IOS version
      debug:
        msg: 
          - "New IOS Version: {{ ios_version }}"

    - name: Check if versions are as expected
      ansible.builtin.assert:
        that:
          - " new_ios_version == ios_version "
        fail_msg: "IOS version after upgrade does not match expected version."
        success_msg: "IOS version after upgrade matches expected version."


