---
- name: Upgrade Install Mode IOS XE Device
  hosts: all
  gather_facts: yes
  vars:
    ansible_command_timeout: 7200
    scp_server: "{{ scp_server }}"
    scp_username: "{{ scp_username }}"
    scp_password: "{{ scp_password }}"
    new_ios_version: "{{ new_ios_version }}"
    new_ios_image: "{{ new_image_name }}"
    new_image_md5: "{{ new_image_md5 }}"
    
  tasks:
    - name: Collect facts to get system information
      ansible.builtin.setup:
        filter:
          - ansible_date_time

    - name: Display collected facts
      debug:
        var: ansible_date_time

    - name: Backup configuration before upgrade
      cisco.ios.ios_command:
        commands: 
          - command: copy running-config startup-config
            prompt: 'Destination filename \[startup-config\]?'
            answer: "\n"
      register: backup_result

    - name: set backup result fact
      ansible.builtin.set_fact:
        backup_result_suceess: "{{ backup_result['stdout_lines'][0][2] }}"

    - name: Send configuration backup to SCP server
      cisco.ios.ios_command:
        commands:
          - command: "copy startup-config scp://{{ scp_username }}:{{ scp_password }}@{{ scp_server }}/{{ inventory_hostname }}_config_{{ ansible_date_time.date }}.cfg\r\r\r"
            prompt: 
              - 'Address or name of remote host .*'
              - 'Destination username .*'
              - 'Destination filename .*'
            answer: 
              - "\r"
      register: scp_backup_result

    - name: Display SCP backup result
      debug:
        var: scp_backup_result

    - name: Check backup success
      ansible.builtin.assert:
        that:
          - "'[OK]' in  backup_result_suceess "
        fail_msg: "Configuration backup failed. Aborting upgrade process."
        success_msg: "Configuration backup successful."

    - name: Show install summary
      cisco.ios.ios_command:
        commands:
          - show install summary
      register: install_summary


    - name: Add new IOS image - install mode
      cisco.ios.ios_command:
        commands:
          - command: install add file flash:/{{ new_ios_image }}
      when: new_ios_version not in install_summary.stdout[0]

    - name: Show install summary
      cisco.ios.ios_command:
        commands:
          - show install summary
      register: install_summary

    
    - name: Display and verify if installation was successful
      ansible.builtin.assert:
        that: 
          - " new_ios_version in install_summary.stdout[0] "
        fail_msg: "IOS XE installation failed or version mismatch."
        success_msg: "IOS XE installation successful and version verified."


    - name: show install activate
      cisco.ios.ios_command:
        commands:
          - show install activate
      register: install_activate


    - name: Activate new IOS image
      cisco.ios.ios_command:
        commands:
          - command: install activate
            prompt: 'This operation may require a reload of the system.*'
            answer: 'y'
      when: new_ios_version not in install_activate.stdout[0]


    - name: Wait for 10 minutes and retry connection
      ansible.builtin.wait_for_connection:
        delay: 600
        timeout: 1800
        sleep: 30

    - name: show install activate
      cisco.ios.ios_command:
        commands:
          - show install activate
      register: install_activate

    - name: Display and verify if installation is activated
      ansible.builtin.assert:
        that:
          - new_ios_version in install_activate.stdout[0]
        fail_msg: "IOS XE installation activation failed."
        success_msg: "IOS XE installation activated successfully."


    - name: Commit new image
      cisco.ios.ios_command:
        commands:
          - command: install commit

    - name: show install committed
      cisco.ios.ios_command:
        commands:
          - show install committed
      register: install_committed

    - name: Display and verify if installation is committed
      ansible.builtin.assert:
        that:
          - new_ios_version in install_committed.stdout[0]
        fail_msg: "IOS XE installation commit failed."
        success_msg: "IOS XE installation committed successfully."