---
- name: Post-check after IOS Upgrade Playbook
  hosts: all
  gather_facts: false
  vars:
    ansible_command_timeout: "{{ ansible_command_timeout }}"
    scp_server: "{{ scp_server }}"
    scp_username: "{{ scp_username }}"
    scp_password: "{{ scp_password }}"
    new_ios_version: "{{ new_ios_version }}"
    new_ios_image: "{{ new_image_name }}"
    new_image_md5: "{{ new_image_md5 }}"
    destination_ping_ip: "{{ destination_ping_ip }}"


  tasks:
    - name: Gather IOS version after upgrade
      cisco.ios.ios_facts:
        gather_subset: hardware
      register: post_upgrade_facts
    
    - name: Validate IOS version
      ansible.builtin.assert:
        that:
          - " post_upgrade_facts.ansible_facts.ansible_net_version == new_ios_version "
        fail_msg: "IOS version after upgrade does not match expected version."
        success_msg: "IOS version after upgrade matches expected version."

    - name: Get up time after upgrade
      cisco.ios.ios_command:
        commands:
          - show version | include uptime
      register: uptime_result

    - name: Display device uptime after upgrade
      debug:
        var: uptime_result.stdout_lines

    - name: Get interface status after upgrade
      cisco.ios.ios_command:
        commands: "show ip interface brief"
      register: post_interface_status
    
    - name: get post check interface up count
      cisco.ios.ios_command:
        commands: "show ip interface brief | count up"
      register: post_interface_up_raw

    - name: Set fact for interface up count
      ansible.builtin.set_fact:
        post_interface_up_count: "{{ (post_interface_up_raw.stdout[0] | regex_search('\\d+$') | int) }}"

    - name: Compare Interface Up Count before and after upgrade
      ansible.builtin.assert:
        that:
          - " post_interface_up_count == workflow_interface_up_count[inventory_hostname] "
        fail_msg: "Number of interfaces in 'up' state has changed after upgrade."
        success_msg: "Number of interfaces in 'up' state is consistent before and after upgrade."

    - name: Get IP Routing Table Summary after upgrade
      cisco.ios.ios_command:
        commands: "show ip route summary"
      register: post_route_raw

    - name: Display IP Routing Table Summary
      debug:
        var: post_route_raw.stdout_lines

    - name: Extract Total Routes (Networks + Subnets)
      ansible.builtin.set_fact:
        post_total_networks: "{{ (post_route_raw.stdout[0] | regex_search('Total.*') | split)[1] }}"
        post_total_subnets: "{{ (post_route_raw.stdout[0] | regex_search('Total.*') | split)[2] }}"

    - name: Compare Total Networks before and after upgrade
      ansible.builtin.assert:
        that:
          - " post_total_networks == workflow_networks[inventory_hostname] "
        fail_msg: "Total networks count has changed after upgrade."
        success_msg: "Total networks count is consistent before and after upgrade."

    - name: Compare Total Subnets before and after upgrade
      ansible.builtin.assert:
        that:
          - " post_total_subnets == workflow_subnets[inventory_hostname] "
        fail_msg: "Total subnets count has changed after upgrade."
        success_msg: "Total subnets count is consistent before and after upgrade."

    - name: Test reachability to Coreswitch after upgrade
      cisco.ios.ios_ping:
        dest: "{{ destination_ping_ip }}"
      register: post_ping_result
      ignore_errors: yes

    - name: Display post-upgrade ping result
      debug:
        var: post_ping_result
        
